#!/bin/bash

export MAKEFLAGS="-j$(grep -c ^processor /proc/cpuinfo)"
mkdir -p ../cpp/build && pushd ../cpp/build

# configure the build using ninja
# see https://arrow.apache.org/docs/developers/cpp/building.html#faster-builds-with-ninja
# no S3 AWS SDK support
cmake -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
 -DCMAKE_INSTALL_LIBDIR=lib \
 -DARROW_WITH_BZ2=$ARROW_WITH_BZ2 \
 -DARROW_WITH_ZLIB=$ARROW_WITH_ZLIB \
 -DARROW_WITH_ZSTD=$ARROW_WITH_ZSTD \
 -DARROW_WITH_LZ4=$ARROW_WITH_LZ4 \
 -DARROW_WITH_SNAPPY=$ARROW_WITH_SNAPPY \
 -DARROW_WITH_BROTLI=$ARROW_WITH_BROTLI \
 -DARROW_PARQUET=$ARROW_PARQUET \
 -DARROW_PYTHON=$ARROW_PYTHON \
 -DARROW_BUILD_TESTS=$ARROW_BUILD_TESTS \
 -DARROW_COMPUTE=$ARROW_COMPUTE \
 -DARROW_CSV=$ARROW_CSV \
 -DARROW_DATASET=$ARROW_DATASET \
 -DARROW_FILESYSTEM=$ARROW_FILESYSTEM \
 -DARROW_JEMALLOC=$ARROW_JEMALLOC \
 -DARROW_JSON=$ARROW_JSON \
 -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
 -DARROW_INSTALL_NAME_RPATH=$ARROW_INSTALL_NAME_RPATH \
 -DARROW_S3=$ARROW_S3 \
 -GNinja \
 ..

cmake --build . --target install

pushd ../../r

